###Data
```{r saved}
#libraries####
library(tidyverse)
library(DT)
library(lubridate)

#meta-data####
meta <- read_csv("data/meta-data.csv")
datatable(meta)

#data####
data.2015 <- read_csv("data/MNP.2015.csv")
data.2016 <- read_csv("data/MNP.2016.csv")

#merge
data <- rbind.data.frame(data.2015, data.2016)

#code treatment properly
data <- data %>% rename(net.treatment = treatment) #%>% na.omit(data) 

#keep key columns and minimize working dataframe
data <- data %>% select(-name, -plant, -start, -stop, -ID, -recorder)

#set year and rep as characters
data$year <- as.character(data$year)
data$rep <- as.character(data$rep)

#convert times to total seconds
data$total.duration <- as.numeric(data$total.duration)
data$visitation.duration <- as.numeric(data$visitation.duration)

#mute all code, will use net.treatment
#tidy data to expand treatment column (current structure is a mix of three factors)
#microsite
#data <- data %>% mutate(microsite = ifelse(net.treatment %in% c("SA", "SAA", "SX"), "Larrea", ifelse(net.treatment %in% c("OA"), "open", ifelse(net.treatment %in% c("AMB"), "Ambrosia", NA))))
#length(unique(data$microsite))

#annuals present
#data <- data %>% mutate(annuals = ifelse(net.treatment %in% c("SA", "SAA"), "annuals", ifelse(net.treatment %in% c("OA"), "annuals", ifelse(net.treatment %in% c("AMB"), "annuals", "none"))))
#length(unique(data$annuals))

#target flowers
#data <- data %>% mutate(target.flowers = ifelse(net.treatment %in% c("SA", "SX"), "shrub flowers", ifelse(net.treatment %in% c("AMB", "SAA", "OA"), "annual plant flowers", "NA")))
#length(unique(data$target.flowers))

#recode net.treatment column
data <- data %>% mutate(net.treatment = ifelse(net.treatment %in% c("SA"), "Larrea flowers with annuals", ifelse(net.treatment %in% c("SX"), "Larrea flowers without annuals", ifelse(net.treatment %in% c("SAA"), "Annual flowers under Larrea",ifelse(net.treatment %in% c("OA"), "Annual flowers in open",ifelse(net.treatment %in% c("AMB"), "Annual flowers under Ambrosia","NA"))))))

#frequency in a separate dataframe####
#frequency <- data %>% group_by(year, day, net.treatment, rep, microsite, annuals, target.flowers) %>% summarise(net.time = sum(total.duration), mean.visitation.duration = mean(visitation.duration), summed.visitation.duration = sum(visitation.duration), mean.floral.density = mean(floral.density), mean.insect.RTU = n_distinct(insect.RTU), count = n())

#frequency <- data %>% group_by(year, day, net.treatment, rep) %>% 
#summarise(net.time = sum(total.duration), mean.visitation.duration = mean(visitation.duration), summed.visitation.duration = sum(visitation.duration), mean.floral.density = mean(floral.density), mean.insect.RTU = n_distinct(insect.RTU), count = n())

#frequency$net.time <- as.numeric(frequency$net.time) #converts to total seconds
#frequency$mean.visitation.duration <- as.numeric(frequency$mean.visitation.duration) #converts to total seconds
#frequency$summed.visitation.duration <- as.numeric(frequency$summed.visitation.duration) #converts to total seconds
#frequency$count <- as.numeric(frequency$count)

#frequency$rate <- as.numeric(frequency$count)/frequency$net.time #weight by net time
#frequency$proportion.visitations <- frequency$mean.visitation.duration/frequency$net.time
#frequency$rate.per.flower <- frequency$count/frequency$mean.floral.density
#datatable(frequency)

#frequency$visitations.hr <- frequency$proportion.visitations*60
#frequency$rate.per.flower.hr <- frequency$rate.per.flower*60

#FILTER OUT ANNUALS VERSUS SHRUB FLOWERS
#frequency.annuals <- frequency %>% filter(target.flowers == "annual plant flowers")
#frequency.shrubs <- frequency %>% filter(target.flowers == "shrub flowers")

#repeat above with RTU as factor####
#frequency.by.RTU <- data %>% group_by(year, day, net.treatment, insect.RTU, rep, microsite, annuals, target.flowers) %>% summarise(net.time = sum(total.duration), mean.visitation.duration = mean(visitation.duration), summed.visitation.duration = sum(visitation.duration), mean.floral.density = mean(floral.density), count = n())

frequency.by.RTU <- data %>% group_by(year, day, net.treatment, rep, insect.RTU) %>% 
  summarise(net.time = sum(total.duration), mean.visitation.duration = mean(visitation.duration), summed.visitation.duration = sum(visitation.duration), mean.floral.density = mean(floral.density), total.floral.density = sum(floral.density), count = n())

#frequency.by.RTU$net.time <- as.numeric(frequency.by.RTU$net.time) #converts to total seconds
#frequency.by.RTU$mean.visitation.duration <- as.numeric(frequency.by.RTU$mean.visitation.duration) #converts to total seconds
#frequency.by.RTU$summed.visitation.duration <- as.numeric(frequency.by.RTU$summed.visitation.duration)
frequency.by.RTU$count <- as.numeric(frequency.by.RTU$count)

#frequency.by.RTU$rate <- as.numeric(frequency.by.RTU$count)/frequency.by.RTU$net.time #weight by net time

#frequency.by.RTU$proportion.visitations <- frequency.by.RTU$mean.visitation.duration/frequency.by.RTU$net.time

#frequency.by.RTU$rate.per.flower <- frequency.by.RTU$count/frequency.by.RTU$mean.floral.density


frequency.by.RTU$rate.per.flower.hr <- (frequency.by.RTU$count/(frequency.by.RTU$mean.floral.density)/(frequency.by.RTU$net.time))*3600

#frequency.by.RTU$visitation.duration.hr <- frequency.by.RTU$summed.visitation.duration*3600

datatable(frequency.by.RTU)

#frequency.by.RTU$visitations.hr <- frequency.by.RTU$proportion.visitations*60
#frequency.by.RTU$rate.per.flower.hr <- frequency.by.RTU$rate.per.flower*60


#split out by year because of non-orthogonality
#freq.2015 <- frequency %>% filter(year == 2015)
#freq.2016 <- frequency %>% filter(year == 2016)

```


### Data visualization
```{r viz, warning=FALSE, message=FALSE}
#Ideal figures for publication.
#Two figures total: 1(a) rate, (b) duration and 2(a) rate per RTU and (b) mean visitation rate per RTU - maybe I think there are other options.  ADD insect.RTU richness

#Higher-order treatment patterns in frequency####
#Collapsed single factor model
ggplot(frequency, aes(net.treatment, rate)) + geom_boxplot() + ylab("visitation rate") + facet_wrap(~year)

ggplot(frequency, aes(net.treatment, count)) + geom_boxplot() + ylab("visitations") + facet_wrap(~year)

ggplot(frequency, aes(net.treatment, rate.per.flower)) + geom_boxplot() + ylab("visitations per flower") + facet_wrap(~year)

ggplot(frequency, aes(net.treatment, proportion.visitations)) + geom_boxplot() + ylab("mean duration of visit per total duration recorded") + facet_wrap(~year)

ggplot(frequency, aes(net.treatment, mean.insect.RTU)) + geom_boxplot() + ylab("mean RTU richness") + facet_wrap(~year)

#net treatment per RTU
ggplot(frequency.by.RTU, aes(net.treatment, rate)) + geom_boxplot() + ylab("visitation rate") + facet_wrap(~insect.RTU*year)

ggplot(frequency.by.RTU, aes(net.treatment, proportion.visitations)) + geom_boxplot() + ylab("mean duration of visit per total duration recorded") + facet_wrap(~insect.RTU*year)

#Treatments separated
ggplot(frequency, aes(microsite, rate, fill = target.flowers)) + geom_boxplot() + facet_wrap(~year) + scale_fill_brewer(palette = "YlGn")

ggplot(frequency, aes(microsite, count, fill = target.flowers)) + geom_boxplot() + facet_wrap(~year) + scale_fill_brewer(palette = "YlGn")

ggplot(frequency, aes(microsite, count, weight = net.time, fill = target.flowers)) + geom_histogram(stat="identity") + facet_wrap(~year) + scale_fill_brewer(palette = "YlGn")

ggplot(frequency, aes(microsite, rate.per.flower, fill = target.flowers)) + geom_boxplot() + facet_wrap(~year) + scale_fill_brewer(palette = "YlGn")

ggplot(frequency, aes(microsite, proportion.visitations, fill = target.flowers)) + geom_boxplot() + facet_wrap(~year) + scale_fill_brewer(palette = "YlGn")

ggplot(frequency, aes(microsite, mean.insect.RTU, fill = target.flowers)) + geom_boxplot() + facet_wrap(~year) + scale_fill_brewer(palette = "YlGn")

#relationships with sampling effort
ggplot(frequency, aes(net.time, count, color = year)) + geom_point()

ggplot(frequency, aes(net.time, count, color = year)) + geom_point() + facet_wrap(~microsite)

#floral density
ggplot(frequency, aes(mean.floral.density, rate, color = microsite)) + geom_point() + facet_wrap(~year)

ggplot(frequency, aes(mean.floral.density, proportion.visitations, color = microsite)) + geom_point() + facet_wrap(~year)

#relationships with sampling effort
ggplot(frequency, aes(net.time, rate, color = year)) + geom_point() + facet_wrap(~microsite*target.flowers)

ggplot(frequency, aes(net.time, mean.visitation.duration, color = year)) + geom_point() + facet_wrap(~microsite*target.flowers)

```

###EDA
```{r EDA, warning=FALSE, message=FALSE}
#test distributions and explore outliers
summary(frequency)
require(fitdistrplus)
descdist(freq.2015$rate, boot = 1000)
descdist(freq.2016$rate, boot = 1000)
detach("package:fitdistrplus", unload = TRUE)

#explore temperature on count and mean visitation rates


```

###Models
```{r models, warning=FALSE, message=FALSE}
#GLM for count and weight by net.time (alt - use MASS and glm.nb)
#library(MASS) #need for glm.nb

#all codes aggregated
#2015 counts
m <- glm(count~net.treatment + mean.floral.density, family = "poisson", weight = net.time, data = freq.2015)
anova(m, test = "Chisq") 

#posthoc test
require(lsmeans)
lsmeans(m, pairwise~net.treatment, adjust="tukey")

#2016 counts
m <- glm(count~net.treatment + mean.floral.density, family = "poisson", weight = net.time, data = freq.2016)
anova(m, test = "Chisq") 

#posthoc test
require(lsmeans)
lsmeans(m, pairwise~net.treatment, adjust="tukey")

#repeat above for mean.visitation.duration
#2015
m <- glm(mean.visitation.duration~net.treatment + mean.floral.density, family = "gaussian", weight = net.time, data = freq.2015)
anova(m, test = "Chisq") 

#posthoc test
require(lsmeans)
lsmeans(m, pairwise~net.treatment, adjust="tukey")

#2016
m <- glm(mean.visitation.duration~net.treatment + mean.floral.density, family = "gaussian", weight = net.time, data = freq.2016)
anova(m, test = "Chisq") 

#posthoc test
require(lsmeans)
lsmeans(m, pairwise~net.treatment, adjust="tukey")

#2015 visitation rates 
#suggestion here to use offset instead ratios http://stats.stackexchange.com/questions/164889/how-to-deal-with-non-integer-warning-from-negative-binomial-glm
m <- glm(rate~net.treatment + mean.floral.density, family = "poisson", data = freq.2015)
anova(m, test = "Chisq") 

#posthoc test
require(lsmeans)
lsmeans(m, pairwise~net.treatment, adjust="tukey")

#2016 visitation rates 
m <- glm(rate~net.treatment + mean.floral.density, family = "poisson", data = freq.2016)
anova(m, test = "Chisq") 

#posthoc test
require(lsmeans)
lsmeans(m, pairwise~net.treatment, adjust="tukey")

#treatments split out
#2015
m <- glm(mean.visitation.duration~microsite*annuals*target.flowers + mean.floral.density, family = "gaussian", weight = net.time, data = freq.2015)
anova(m, test = "Chisq") 

lsmeans(m, pairwise~microsite*annuals*target.flowers, adjust="tukey")

#2016
m <- glm(mean.visitation.duration~microsite*annuals*target.flowers + mean.floral.density, family = "gaussian", weight = net.time, data = freq.2016)
anova(m, test = "Chisq") 

lsmeans(m, pairwise~microsite*annuals*target.flowers, adjust="tukey")

#2015
m <- glm(rate~microsite*annuals*target.flowers + mean.floral.density, family = "gaussian", weight = net.time, data = freq.2015)
anova(m, test = "Chisq") 

lsmeans(m, pairwise~microsite*annuals*target.flowers, adjust="tukey")

#2016
m <- glm(rate~microsite*annuals*target.flowers + mean.floral.density, family = "gaussian", weight = net.time, data = freq.2016)
anova(m, test = "Chisq") 

lsmeans(m, pairwise~microsite*annuals*target.flowers, adjust="tukey")

#2015
m <- glm(rate.per.flower~microsite*annuals*target.flowers + mean.floral.density, family = "gaussian", weight = net.time, data = freq.2015)
anova(m, test = "Chisq") 

lsmeans(m, pairwise~microsite*annuals*target.flowers, adjust="tukey")

#2016
m <- glm(rate.per.flower~microsite*annuals*target.flowers + mean.floral.density, family = "gaussian", weight = net.time, data = freq.2016)
anova(m, test = "Chisq") 

lsmeans(m, pairwise~microsite*annuals*target.flowers, adjust="tukey")

#2015
m <- glm(mean.insect.RTU~microsite*annuals*target.flowers + mean.floral.density, family = "gaussian", weight = net.time, data = freq.2015)
anova(m, test = "Chisq") 

lsmeans(m, pairwise~microsite*annuals*target.flowers, adjust="tukey")

#2016
m <- glm(mean.insect.RTU~microsite*annuals*target.flowers + mean.floral.density, family = "gaussian", weight = net.time, data = freq.2016)
anova(m, test = "Chisq") 

lsmeans(m, pairwise~microsite*annuals*target.flowers, adjust="tukey")

#Then test RTU nested within rep
#too many levels

#Then test in ONE model, frequency, with year as a factor.

```
